# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 592c2d9c126a0d7f1f32cc10aee2dcec020b1079010509aaaf70961b3d82773b605eb41c35cc2a761a65d14637ca3ddcc77468e45d78655f504ceefca9ebaa68

test:
  secret_key_base: 2fd1000688d36c0e2dbfcc3e0863b844cf35c09e5f2575eb8e956f3301e97a36f747582883456f44859beabd1f9d8949bdee7a97ad3ebe2a26982db010f101ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
